spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:h2:tcp://localhost/~/maple
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
#  file:
#    name: logs/application.log
#  org.hibernate.type: trace